[package]
name = "req_guard"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
notify = "8.0.0"
once_cell = "1.20.3"
regex = "1.11.1"
serde = { version = "1.0.218", features = ["derive"] }
toml = "0.8.20"
